// <auto-generated />
namespace OtherSquare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newdatamodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdatamodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201912221900275_new data models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
