// <auto-generated />
namespace OtherSquare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addisSelectedtoSubjectandCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addisSelectedtoSubjectandCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202001230046112_add isSelected to Subject and Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
