// <auto-generated />
namespace OtherSquare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removeIsArchivedfromFlashcardmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeIsArchivedfromFlashcardmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202002231751548_remove IsArchived from Flashcard model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
